### ISSUE TITLE
Error after logging in

### ISSUE THREAD

**Issue by camer0nluo** [Shaun-Regenbaum/OneUSGAutomaticClock#2]
I ran into this error right after the script enters my username and password. Do you have any idea what problem it could be? Thanks
![Screen Shot 2021-01-04 at 8 31 28 @Shaun-Regenbaum PM](https://user-images.githubusercontent.com/69396582/103535534-d8597100-4ecb-11eb-9491-095c15e184ed.png)

**Comment by Shaun-Regenbaum** [comment]
Hi I have been noticing this issue as well. I'm going to investigate later today and post a fix. Thanks for opening it!

**Comment by Shaun-Regenbaum** [comment]
Hi I have been noticing this issue as well. I'm going to investigate later today and post a fix. Thanks for opening it!

**Comment by Shaun-Regenbaum** [comment]
I have tried to replicate the issue today, but it seems to have disappeared. Are you still experiencing the problem?

The bug originates in GT's login form (so not connected to OneUSG), but it would help to know more information about your setup, what browser are you using?

If the issue has disappeared for you as well, then it might have been due to some maintenance on GT's login form backend.
Let me know!
Thanks!

**Comment by camer0nluo** [comment]
I still have this problem sadly.
My browser is chrome, big sur version of Macbook Pro.
Thanks!

**Comment by Shaun-Regenbaum** [comment]
Aha, it may be an error with the mac version of the Chrome driver. I have some ideas of things to try. I get back tomorrow night from a small trip, so will post a fix by Sunday. Thanks for following up so quickly!

**Comment by camer0nluo** [comment]
Thanks for your help.  Have a nice trip, school is starting soon!!

**Comment by Shaun-Regenbaum** [comment]
# Found a Solution!
So I found that the issue was with a faulty chrome driver, I have resolved it by using a new python package called chromedriver_autoinstaller that will automatically install/update the correct driver for both your OS and chrome version every time. 

This will also eliminate the need to add anything to your path which makes the set-up one step less complicated! 

Could you clone the repo once again and then type the following into your terminal:
`pip install chromedriver_autoinstaller`

If this resolves the issue, please let me know! Otherwise I'll hack at it more tomorrow!

**Comment by camer0nluo** [comment]
Still redirects me to the error page, although this time the duo shows up right before the error page!
I'll also trying hacking at it as well. Thanks!!

**Comment by Shaun-Regenbaum** [comment]
How long does the duo page show up for?

**Comment by camer0nluo** [comment]
Less than 10 seconds, and it redirects to the error page.

**Comment by Shaun-Regenbaum** [comment]
How long does the duo page show up for? I just ran the script on a macbook and it worked, so it must be something more specific. What version of Python are you running?

**Comment by camer0nluo** [comment]
The duo page shows up for a couple of seconds, and the version i'm using is Python 3.7

**Comment by camer0nluo** [comment]
Would is be a system error? Are you also using Big Sur?

**Comment by Shaun-Regenbaum** [comment]
I am also using Big Sur (that is the latest one right? I am running on the m1 chip). Could you try update python to 3.9 from [here](https://www.python.org/downloads/release/python-390/)? That may be an issue (there were some wierd bugs in some 3.7 releases that I used to encounter, so its just a hunch).

**Comment by camer0nluo** [comment]
Ah, it was the python's version issue. Thanks for your help, I can finally use your tool. Very helpful

**Comment by Shaun-Regenbaum** [comment]
Im glad I could help! Getting feedback really does make one's day!
